### ISSUE TITLE
Missing behavior_tree_editor file

### ISSUE THREAD

**Issue by TonyChung-A001** [BTIRAI/btirai.github.io#4]
Pac-Man 
Ubuntu 20.04 environment
------------------------------------
result:
bash: ./behavior_tree_editor: No such file or directory
----------------------------------------
Detail:
tonychung@ros-1-2:~/Work/pacman/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tonychung/Work/pacman/build

tonychung@ros-1-2:~/Work/pacman/build$ make
[  2%] Automatic MOC for target qt_node_editor
[  2%] Built target qt_node_editor_autogen
[ 69%] Built target qt_node_editor
[ 71%] Automatic MOC for target behavior_tree_editor
[ 71%] Built target behavior_tree_editor_autogen
[100%] Built target behavior_tree_editor

tonychung@ros-1-2:~/Work/pacman/build$ cd bt_editor/

tonychung@ros-1-2:~/Work/pacman/build/bt_editor$ ./behavior_tree_editor
bash: ./behavior_tree_editor: No such file or directory

tonychung@ros-1-2:~/Work/pacman/build/bt_editor$ ls
behavior_tree_editor_autogen  libqt_node_editor.a  qt_nodeditor            ui_condition_form.h
CMakeFiles                    Makefile             qt_node_editor_autogen  ui_mainwindow.h
cmake_install.cmake           qrc_resources.cpp    ui_action_form.h

tonychung@ros-1-2:~/Work/pacman/build/bt_editor$

**Comment by miccol** [comment]
can you do an `ls` into the `build` folder and share the output?

**Comment by TonyChung-A001** [comment]
![Screenshot from 2021-11-14 06-38-41](https://user-images.githubusercontent.com/35799407/142550967-5111eb1a-fbd4-46bf-9446-2e14a26cec31.png
![Screenshot from 2021-11-14 06-42-32](https://user-images.githubusercontent.com/35799407/142551001-7419be22-11e5-4bff-94f4-0806bab98b15.png)
)

**Comment by miccol** [comment]
can you provide the entire output of a **clean** `cmake ..` and  `make`

**Comment by TonyChung-A001** [comment]
Did you open or click the link "https://user-images.githubusercontent.com/35799407/142550967-5111eb1a-fbd4-46bf-9446-2e14a26cec31.png"?
I don't know that GitHub only show the second png file. And It don't show the first PNG.

**Comment by miccol** [comment]
any update on this?
